language: ruby

rvm: '2.5.0'

before_script:
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:migrate RAILS_ENV=test
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 10

script:
  - bundle exec rspec
